name: Add Affiliation to LTB Map
description: Use this template to request adding your affiliation to the LTB map.
body:
  - type: markdown
    attributes:
      value: |
        Please provide the details of your affiliation to be added to the LTB map. Ensure all information is accurate and complete.

  - type: input
    id: name
    attributes:
      label: Name
      description: |
        Enter the name of the affiliation (e.g., University of Tennessee Knoxville).
        (Commas in the name will be removed to avoid parsing issues; hyphens are okay.)
    validations:
      required: true

  - type: input
    id: latitude
    attributes:
      label: Latitude
      description: |
        Enter the latitude coordinate (e.g., 35.9517).
    validations:
      required: true

  - type: input
    id: longitude
    attributes:
      label: Longitude
      description: |
        Enter the longitude coordinate (e.g., -83.9300).
    validations:
      required: true

  - type: dropdown
    id: marker-symbol
    attributes:
      label: Marker Symbol
      description: |
        Select the affiliation type.
    options:
      - university
      - lab
      - company
      - non-profit
    validations:
      required: false

  - type: input
    id: new-affiliation-type
    attributes:
      label: New Affiliation Type
      description: |
        If you want to add a new affiliation type that is not listed above, please specify it here.
    validations:
      required: false

  - type: dropdown
    id: info
    attributes:
      label: Additional Information
      description: |
        Provide additional information about the affiliation (e.g., Sponsor, Developer, Publication).
    options:
      - Sponsor (has research projects or contracts with LTB)
      - Developer (has contributed to the LTB codebase)
      - Publication (has published research that used LTB)
    validations:
      required: true
