name: Add Affiliation to LTB Map
description: Use this template to request adding your affiliation to the LTB map.
body:
  - type: markdown
    attributes:
      value: |
        Suggested issue name: Add Affiliation to LTB Map: [Your Affiliation Name Here].
        Please provide the details of your affiliation.

  - type: textarea
    id: name
    attributes:
      label: Name
      description: |
        Enter the name of the affiliation, e.g., University of Tennessee Knoxville.
        Commas in the name will be removed to avoid parsing issues, but hyphens are okay.
    validations:
      required: false

  - type: input
    id: Latitude
    attributes:
      label: Latitude
      description: Enter the latitude coordinate, e.g., 35.9517
    validations:
      required: false

  - type: input
    id: Longitude
    attributes:
      label: Longitude
      description: Enter the longitude coordinate, e.g., -83.9300
    validations:
      required: false

  - type: dropdown
    id: affiliation-type
    attributes:
      label: Affiliation Type
      options:
        - "1 for university"
        - "2 for lab"
        - "3 for company"
        - "4 for non-profit"

  - type: input
    id: new-affiliation-type
    attributes:
      label: New Affiliation Type
      description: None of above affiliation types? Please specify here.
    validations:
      required: false

  - type: checkboxes
    id: usage-info
    attributes:
      label: Usage Information
      description: How you use the LTB? Select all that apply.
      options:
        - label: "0 for Sponsor (if you have sponsored LTB)"
          required: false
        - label: "1 for Developer (if you believe you have contributed to the codebase)"
          required: false
        - label: "2 for Contract User (if you have a contract with LTB)"
          required: false
        - label: "3 for Publication User (if you have publications using LTB, DOIs are encouraged to be provided below)"
          required: false
        - label: "4 for General User (if you use LTB for research or teaching)"
          required: false
    validations:
      required: false

  - type: textarea
    id: dois
    attributes:
      label: DOIs
      description: |
        If you have publications using LTB, please share the DOIs. Separate multiple DOIs with commas. For example:
        10.1109/ABCD.1234.56789
        or
        10.1109/ABCD.1234.56789, 10.1109/ABCD.4321.98765
    validations:
      required: false