name: Add Affiliation to LTB Map
description: Use this template to request adding your affiliation to the LTB map.
body:
  - type: markdown
    attributes:
      value: |
        Please provide the details of your affiliation to be added to the LTB map.
        Ensure all information is accurate and complete.

  - type: textarea
    id: name
    attributes:
      label: Name
      description: |
        Enter the name of the affiliation, e.g., University of Tennessee Knoxville.
        Commas in the name will be removed to avoid parsing issues, but hyphens are okay.
    validations:
      required: false

  - type: input
    id: Latitude
    attributes:
      label: Description of the unexpected behavior
      description: Enter the latitude coordinate, e.g., 35.9517
    validations:
      required: false

  - type: input
    id: Longitude
    attributes:
      label: Longitude
      description: Enter the longitude coordinate, e.g., -83.9300
    validations:
      required: false

  - type: dropdown
    id: affiliation-type
    attributes:
      label: Affiliation Type
      options:
        - "1 for university"
        - "2 for lab"
        - "3 for company"
        - "4 for non-profit"