name: Add Showcase
description: Use this template to add a new showcase page for a project using LTB.
body:
  - type: markdown
    attributes:
      value: |
        Suggested issue name: Add Showcase: [Your Showcase Title Here]
        An example can be [ev-deliverable-provision-of-sfr.md](https://github.com/CURENT/curent.github.io/blob/master/_showcase/ev-deliverable-provision-of-sfr.md)

  - type: textarea
    id: name
    attributes:
      label: Name
      description: |
        Enter the name of the showcase affiliation, e.g., University of Tennessee, Knoxville.
    validations:
      required: false