name: Add Showcase
description: Use this template to add a new showcase page for research using LTB.
body:
  - type: markdown
    attributes:
      value: |
        Suggested issue name: Add Showcase: [Your Showcase Title Here]