name: Bug Report 2
description: Use this template to request adding your affiliation to the LTB map.
body:
  - type: markdown
    attributes:
      value: |
        Please provide the details of your affiliation to be added to the LTB map.
        Ensure all information is accurate and complete.

  - type: textarea
    id: typo-description
    attributes:
      label: Description of the typo or inaccurate information
      description: |
        Describe the typo or inaccurate information with the following details:

        - What is the incorrect information?
        - What is the correct information?
        - Where is the typo located? (e.g., page URL, section, paragraph)
    validations:
      required: false

  - type: textarea
    id: unexpected-behavior
    attributes:
      label: Description of the unexpected behavior
      description: |
        Describe the unexpected behavior with the following details:

        - What did you expect to happen?
        - What actually happened?
    validations:
      required: false